export const SET_USER = 'SET_USER';
export const UPDATE_ACCESS_TOKEN = 'UPDATE_ACCESS_TOKEN';
export const LOGOUT = 'LOGOUT';

export const SET_SIDEBAR_ROUTES = 'SET_SIDEBAR_ROUTES';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const CHANGE_BREAKPOINT = 'CHANGE_BREAKPOINT';
