export const SET_TOKENS = 'SET_TOKENS';
export const SET_USER = 'SET_USER';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const UPDATE_ACCESS_TOKEN = 'UPDATE_ACCESS_TOKEN';
export const LOGOUT = 'LOGOUT';
//

export const SET_SIDEBAR_ROUTES = 'SET_SIDEBAR_ROUTES';
export const UPDATE_BREADCRUMBS = 'UPDATE_BREADCRUMBS'; // [USSTRNSTD]
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const CHANGE_BREAKPOINT = 'CHANGE_BREAKPOINT';
//
