export const LOCAL_STATE_LOADED = 'LOCAL_STATE_LOADED';
export const ROUTES_LOADED = 'ROUTES_LOADED';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const READY_FOR_SIDEBAR_ROUTES = 'READY_FOR_SIDEBAR_ROUTES';
export const NAVIGATE = 'NAVIGATE';
//
